/*
 * The wire shapes for live camera/screen negotiation, and the whitelist
 * parsers that are the only sanctioned way to turn a peer-supplied payload
 * into one of them.
 *
 * Same threat model as shared/device.ts: these frames are AEAD-sealed, so
 * the relay cannot have forged them, but the peer holds the same session
 * key and `decodeControl` (client/protocol.ts) is a bare
 * `JSON.parse(...) as ControlMessage` with no runtime validation. Every
 * field below is therefore whatever the other browser felt like putting
 * there — and unlike a device label, this one is headed straight for
 * `RTCPeerConnection.setRemoteDescription` / `addIceCandidate`. Each parser
 * builds a fresh object out of known-good fields; none ever casts the input
 * and hands it through.
 */

export type MediaKind = 'camera' | 'screen';

export interface MediaOffer {
  sdp: string;
  kind: MediaKind;
}

export interface MediaAnswer {
  sdp: string;
}

export interface MediaIce {
  candidate: string;
  sdpMid?: string;
  sdpMLineIndex?: number;
  usernameFragment?: string;
}

/**
 * A real SDP, as generated by a browser's own `createOffer`/`createAnswer`,
 * runs to a few kilobytes even with a generous pile of codecs and ICE
 * candidates. 64 KiB is generous headroom above that, not a realistic
 * ceiling — a peer sending more than this is not describing a media
 * session, it is trying to make the receiving tab hold megabytes of text
 * it will only fail to parse as SDP.
 */
const MAX_SDP_CHARS = 64 * 1024;

/**
 * RFC 8445 bounds a ufrag to 4-256 bits of base64 — a browser's own
 * candidates run a handful of characters. 256 is headroom above the
 * spec's own ceiling, not a realistic one; same reasoning as
 * MAX_SDP_CHARS, applied to a much smaller field.
 */
const MAX_UFRAG_CHARS = 256;

function isMediaKind(value: unknown): value is MediaKind {
  return value === 'camera' || value === 'screen';
}

function parseSdp(raw: Record<string, unknown>): string | undefined {
  const { sdp } = raw;
  if (typeof sdp !== 'string' || sdp.length > MAX_SDP_CHARS) return undefined;
  return sdp;
}

/**
 * Parses an untrusted payload into a `MediaOffer`, or undefined if it isn't
 * one.
 *
 * `kind` has no default. A default would let a peer say "camera" in the UI
 * while actually sending a screen capture — a small lie, but one the user
 * on the other end reads as a fact about what they are about to see. Better
 * to refuse the whole offer than render a label that isn't true.
 */
export function parseMediaOffer(value: unknown): MediaOffer | undefined {
  if (typeof value !== 'object' || value === null) return undefined;
  const raw = value as Record<string, unknown>;

  const sdp = parseSdp(raw);
  if (sdp === undefined) return undefined;
  if (!isMediaKind(raw.kind)) return undefined;

  return { sdp, kind: raw.kind };
}

/**
 * Parses an untrusted payload into a `MediaAnswer`, or undefined if it
 * isn't one. An answer carries no `kind` — the offerer already knows what
 * it asked for, and the answer only ever confirms the SDP for it.
 */
export function parseMediaAnswer(value: unknown): MediaAnswer | undefined {
  if (typeof value !== 'object' || value === null) return undefined;
  const raw = value as Record<string, unknown>;

  const sdp = parseSdp(raw);
  if (sdp === undefined) return undefined;

  return { sdp };
}

/**
 * Parses an untrusted payload into a `MediaIce`, or undefined if it isn't
 * one.
 *
 * `usernameFragment` is kept, not stripped — it used to be dropped here on
 * the theory that `addIceCandidate` doesn't strictly need it (the
 * connection already knows its remote ufrag from the SDP). That reasoning
 * missed what the field is actually *for*: a browser uses a candidate's
 * ufrag to bind it to the ICE generation it was gathered for. Per
 * webrtc-pc, a candidate whose `usernameFragment` doesn't match the
 * currently-applied remote description makes `addIceCandidate` *reject*
 * with `OperationError` — not silently ignore it, which is what an
 * earlier version of this comment claimed. Stripping the field here threw
 * away the only thing that lets the browser tell a stale candidate apart
 * from a current one at all; see LiveSession's glare handling
 * (client/media/live-session.ts), where a peer's abandoned negotiation
 * attempt can still have trickled a few candidates before it was
 * abandoned. Passing the ufrag through lets the browser recognise those as
 * belonging to a generation that's no longer current and reject them
 * itself — `MediaPeer` (client/media/media-peer.ts) treats that rejection
 * as the expected, non-fatal outcome it is, rather than this code needing
 * to track negotiation generations to do the same job by hand. (Worth
 * confirming against a real browser, per the plan's Verification section,
 * in case some implementation instead ignores a mismatched candidate
 * silently — the non-fatal handling on the receiving end is correct
 * either way.)
 */
export function parseMediaIce(value: unknown): MediaIce | undefined {
  if (typeof value !== 'object' || value === null) return undefined;
  const raw = value as Record<string, unknown>;

  const { candidate, sdpMid, sdpMLineIndex, usernameFragment } = raw;
  if (typeof candidate !== 'string') return undefined;
  if (sdpMid !== undefined && typeof sdpMid !== 'string') return undefined;
  if (sdpMLineIndex !== undefined && typeof sdpMLineIndex !== 'number') return undefined;
  if (usernameFragment !== undefined && (typeof usernameFragment !== 'string' || usernameFragment.length > MAX_UFRAG_CHARS)) {
    return undefined;
  }

  const ice: MediaIce = { candidate };
  if (sdpMid !== undefined) ice.sdpMid = sdpMid;
  if (sdpMLineIndex !== undefined) ice.sdpMLineIndex = sdpMLineIndex;
  if (usernameFragment !== undefined) ice.usernameFragment = usernameFragment;
  return ice;
}
