import { describe, expect, it, vi } from 'vitest';
import { createPeerProxy } from '../../client/worker/peer-proxy.js';
import { HIGH_WATER_BYTES } from '../../client/transport/types.js';
import type { FromWorker } from '../../client/worker/messages.js';

function harness() {
  const posted: FromWorker[] = [];
  const proxy = createPeerProxy((msg) => { posted.push(msg); });
  const transport = proxy.createTransport(true, () => undefined);
  const id = (posted.find((m) => m.t === 'peer-open') as { id: number }).id;
  return { posted, proxy, transport, id };
}

describe('ProxyUpgradeTransport bufferedAmount', () => {
  /*
   * The reason this accounting exists at all: Transport.bufferedAmount is a
   * SYNCHRONOUS getter, Sender.#awaitDrain reads it per chunk, and the real
   * buffer lives on the page. Guessing low would overrun it.
   */
  it('counts every byte sent as outstanding until the page reports otherwise', () => {
    const { transport } = harness();
    expect(transport.bufferedAmount).toBe(0);
    transport.send(new Uint8Array(600));
    transport.send(new Uint8Array(400));
    expect(transport.bufferedAmount).toBe(1000);
  });

  it('drops bytes the page has confirmed accepting, keeping later ones outstanding', () => {
    const { proxy, transport, id } = harness();
    transport.send(new Uint8Array(600));   // seq 1
    transport.send(new Uint8Array(400));   // seq 2
    // The page took seq 1 and its channel then read 100 bytes buffered.
    proxy.handle({ t: 'peer-drain', id, acceptedSeq: 1, bufferedAmount: 100 });
    // 100 really buffered + 400 still in flight to the page.
    expect(transport.bufferedAmount).toBe(500);
  });

  it('over-estimates rather than under-estimates when a report is stale', () => {
    const { proxy, transport, id } = harness();
    transport.send(new Uint8Array(1000));
    proxy.handle({ t: 'peer-drain', id, acceptedSeq: 0, bufferedAmount: 0 });
    // The report predates the send, so the bytes must still count.
    expect(transport.bufferedAmount).toBe(1000);
  });

  it('fires onDrain when the page reports a drain', () => {
    const { proxy, transport, id } = harness();
    const drained = vi.fn();
    transport.onDrain(drained);
    proxy.handle({ t: 'peer-drain', id, acceptedSeq: 0, bufferedAmount: 0 });
    expect(drained).toHaveBeenCalledOnce();
  });

  /*
   * The complement of the test above, and the one that actually pins the
   * behaviour down. Alone, "fires onDrain when the page reports a drain"
   * passes just as happily against a proxy that fires onDrain on every
   * report whatever the buffer says — which is exactly what it used to do,
   * and which silently disabled backpressure on the entire proxy path: the
   * page reports on every `peer-send`, `Sender.#awaitDrain` resolves all its
   * waiters from that callback without re-reading `bufferedAmount`, so the
   * report generated by the frame that pushed the sender over the mark was
   * what immediately unparked it. See the `peer-drain` arm in peer-proxy.ts.
   */
  it('does NOT fire onDrain while the page still reports a full buffer', () => {
    const { proxy, transport, id } = harness();
    const drained = vi.fn();
    transport.onDrain(drained);
    // One byte over the mark, which is the first value that is genuinely
    // "still backed up" — see the boundary test below for why `HIGH_WATER_BYTES`
    // itself is NOT that value.
    proxy.handle({ t: 'peer-drain', id, acceptedSeq: 0, bufferedAmount: HIGH_WATER_BYTES + 1 });
    expect(drained).not.toHaveBeenCalled();
    // Still nothing: over the mark is over the mark, however it is composed.
    proxy.handle({ t: 'peer-drain', id, acceptedSeq: 0, bufferedAmount: HIGH_WATER_BYTES * 4 });
    expect(drained).not.toHaveBeenCalled();
    // And it does fire the moment the real buffer falls below it.
    proxy.handle({ t: 'peer-drain', id, acceptedSeq: 0, bufferedAmount: HIGH_WATER_BYTES - 1 });
    expect(drained).toHaveBeenCalledOnce();
  });

  /*
   * The boundary is inclusive, and that is not a detail — a strict `<` here
   * deadlocks the transfer outright.
   *
   * `RTCDataChannel` fires `bufferedamountlow` on the EDGE from
   * `> bufferedAmountLowThreshold` to `<= threshold` (WebRTC 1.0 §6.2), and
   * `WebRTCTransport` sets that threshold to `HIGH_WATER_BYTES` exactly. Data
   * frames are exactly MAX_FRAME_BYTES and HIGH_WATER_BYTES is exactly 16 of
   * them, so the report that carries the crossing holds exactly
   * HIGH_WATER_BYTES — the mark itself. Reject that report and there is no
   * second chance: the event is edge-triggered, and a parked sender issues no
   * more sends, so no more per-send reports arrive either.
   */
  it('fires onDrain on a report that lands exactly on the mark, where the platform fires', () => {
    const { proxy, transport, id } = harness();
    const drained = vi.fn();
    transport.onDrain(drained);
    proxy.handle({ t: 'peer-drain', id, acceptedSeq: 0, bufferedAmount: HIGH_WATER_BYTES });
    expect(drained).toHaveBeenCalledOnce();
  });

  it('weighs frames still in flight to the page when deciding to fire onDrain', () => {
    const { proxy, transport, id } = harness();
    const drained = vi.fn();
    transport.onDrain(drained);
    // The page's own reading is under the mark, but the worker has already
    // handed it far more that it has not confirmed taking yet. The gate must
    // read the *estimate* — what Sender.#awaitDrain itself consults — and not
    // the raw reported number, or the sender would be woken straight into a
    // bufferedAmount that is still over the mark.
    transport.send(new Uint8Array(HIGH_WATER_BYTES));
    proxy.handle({ t: 'peer-drain', id, acceptedSeq: 0, bufferedAmount: 1000 });
    expect(drained).not.toHaveBeenCalled();
  });

  it('delivers inbound frames in arrival order', () => {
    const { proxy, transport, id } = harness();
    const seen: number[] = [];
    transport.onMessage((f) => seen.push(f[0]!));
    proxy.handle({ t: 'peer-message', id, frame: new Uint8Array([1]) });
    proxy.handle({ t: 'peer-message', id, frame: new Uint8Array([2]) });
    expect(seen).toEqual([1, 2]);
  });

  it('reports a close exactly once and stops sending afterwards', () => {
    const { posted, proxy, transport, id } = harness();
    const closed = vi.fn();
    transport.onClose(closed);
    proxy.handle({ t: 'peer-closed', id, reason: 'connection lost' });
    proxy.handle({ t: 'peer-closed', id, reason: 'connection lost' });
    expect(closed).toHaveBeenCalledOnce();
    const before = posted.length;
    transport.send(new Uint8Array(10));
    expect(posted.length).toBe(before);
  });

  it('resolves whenOpen from the page answer and rejects a timeout distinctly', async () => {
    const a = harness();
    const openA = a.transport.whenOpen(50);
    a.proxy.handle({ t: 'peer-opened', id: a.id, ok: true });
    await expect(openA).resolves.toBeUndefined();

    const b = harness();
    const openB = b.transport.whenOpen(50);
    b.proxy.handle({ t: 'peer-opened', id: b.id, ok: false, reason: 'timeout' });
    await expect(openB).rejects.toThrow(/did not open/i);
  });

  it('fails every pending open when the session is torn down', async () => {
    const { proxy, transport } = harness();
    const open = transport.whenOpen(1000);
    proxy.closeAll('the session was closed');
    await expect(open).rejects.toThrow(/session was closed/);
  });

  it('does not clobber bufferedAmount downward on a stale drain report', () => {
    const { proxy, transport, id } = harness();
    transport.send(new Uint8Array(600));   // seq 1
    transport.send(new Uint8Array(400));   // seq 2
    // Process a good report: page took seq 1 and has 100 bytes buffered.
    proxy.handle({ t: 'peer-drain', id, acceptedSeq: 1, bufferedAmount: 100 });
    expect(transport.bufferedAmount).toBe(500); // 100 buffered + 400 in flight
    // A stale report arrives, claiming seq 0 was taken and 0 bytes buffered.
    // This predates the good report and must not overwrite the 100.
    proxy.handle({ t: 'peer-drain', id, acceptedSeq: 0, bufferedAmount: 0 });
    // Should not drop to 1000 (which would be 0 + 1000 in flight).
    // Must stay at 500 (the good report's 100 + 400 not yet confirmed).
    expect(transport.bufferedAmount).toBe(500);
  });

  /*
   * The relay is this project's declared active adversary, and it drives the
   * upgrade trigger directly: a synthesised `peer-left`/`peer-joined` pair
   * makes Session clear `#upgradeAttempt` and start a fresh one, minting a
   * fresh ProxyUpgradeTransport every cycle. The map used to be emptied only
   * by `closeAll`, so that grew without bound for the life of the worker.
   *
   * Retirement has no public getter, so it is observed through the one arm
   * of `handle` that a closed connection would still act on: `peer-signal-out`
   * reads the `sendSignal` the factory was given and has no `#closed` guard
   * of its own, so it is forwarded if and only if the id is still mapped.
   */
  it('retires a connection from its map when the page reports it closed', () => {
    const posted: FromWorker[] = [];
    const signals: unknown[] = [];
    const proxy = createPeerProxy((msg) => { posted.push(msg); });
    proxy.createTransport(true, (payload) => signals.push(payload));
    const id = (posted.find((m) => m.t === 'peer-open') as { id: number }).id;

    proxy.handle({ t: 'peer-signal-out', id, payload: 'while live' });
    expect(signals).toEqual(['while live']);

    proxy.handle({ t: 'peer-closed', id, reason: 'connection lost' });
    proxy.handle({ t: 'peer-signal-out', id, payload: 'after close' });
    expect(signals).toEqual(['while live']);
  });

  it('retires a connection from its map when the worker closes it', () => {
    const posted: FromWorker[] = [];
    const signals: unknown[] = [];
    const proxy = createPeerProxy((msg) => { posted.push(msg); });
    const transport = proxy.createTransport(true, (payload) => signals.push(payload));
    const id = (posted.find((m) => m.t === 'peer-open') as { id: number }).id;

    transport.close();
    proxy.handle({ t: 'peer-signal-out', id, payload: 'after close' });
    expect(signals).toEqual([]);
  });

  it('stops routing inbound frames once the connection is closed', () => {
    const { proxy, transport, id } = harness();
    const seen: number[] = [];
    transport.onMessage((f) => seen.push(f[0]!));
    proxy.handle({ t: 'peer-message', id, frame: new Uint8Array([1]) });
    proxy.handle({ t: 'peer-closed', id, reason: 'connection lost' });
    // Harmless after a swap or a fallback, but after Session.close() the
    // callback still points at Session.#route — a closed session must not be
    // routing frames at all.
    proxy.handle({ t: 'peer-message', id, frame: new Uint8Array([2]) });
    expect(seen).toEqual([1]);
  });

  it('rejects whenOpen() called after the transport is closed', async () => {
    const { proxy, transport, id } = harness();
    proxy.handle({ t: 'peer-closed', id, reason: 'connection lost' });
    // Now call whenOpen on a closed transport.
    const openAfterClose = transport.whenOpen(1000);
    await expect(openAfterClose).rejects.toThrow(/connection lost/);
  });
});
